# Generated by Django 4.2 on 2024-09-11 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/')),
                ('actual_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warranty_period', models.CharField(max_length=100)),
                ('seller_image', models.ImageField(upload_to='sellers/')),
                ('seller_logo', models.ImageField(upload_to='sellers/logos/')),
                ('rating', models.FloatField()),
            ],
        ),
    ]
