# Generated by Django 4.2 on 2024-09-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller_image',
        ),
        migrations.AddField(
            model_name='product',
            name='seller_img',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_logo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/logos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='warranty_period',
            field=models.CharField(max_length=255),
        ),
    ]
